### ISSUE TITLE
Static files are not loaded when DEBUG=False

### ISSUE THREAD

**Issue by pannlnwza** [BioB3/ku-polls#48]

**Comment by BioB3** [comment]
You normally set DEBUG=False when the app is deployed. According to [this](https://stackoverflow.com/questions/5836674/why-does-debug-false-setting-make-my-django-static-files-access-fail),  the production web server (e.g. Apache, Nginx) is supposed to load static files instead of Django. If you want the static files to load while the app is in local, you could try adding STATIC_ROOT in settings.py or use [WhiteNoise](https://whitenoise.readthedocs.io/en/stable/).
